CREATE TABLE "de_tai" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ngay_tao" timestamptz,
  "trang_thai" varchar(100),
  "trang_thai_duyet" varchar(100),
  "giai_doan" varchar(100),
  "ten_tieng_viet" text,
  "ten_tieng_anh" text,
  "mo_ta" text,
  "yeu_cau_va_so_lieu" text,
  "tai_lieu_tham_khao" text,
  "ma_de_tai" varchar(100) UNIQUE,
  "nhom_nganh" varchar(255),
  "he_dao_tao" varchar(255),
  "so_luong_sinh_vien" int,
  "so_sinh_vien_dang_ky" int,
  "id_tai_khoan_de_xuat" int
);

CREATE TABLE "thuoc_ve" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trang_thai" varchar(255),
  "id_de_tai" int,
  "id_hoc_ky" int
);

CREATE TABLE "thong_bao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tieu_de" varchar(255),
  "noi_dung" text,
  "duong_dan" text,
  "loai_nguoi_nhan" varchar(150),
  "loai_thong_bao" varchar(150),
  "pham_vi" varchar(100)
);

CREATE TABLE "mau_danh_gia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "loai_mau" varchar(255),
  "giai_doan" varchar(255),
  "ten_mau" text UNIQUE,
  "ghi_chu" text
);

CREATE TABLE "nhom_tieu_chi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_nhom" text UNIQUE,
  "id_mau_danh_gia" int
);

CREATE TABLE "tieu_chi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten" text,
  "loai_diem" varchar(255),
  "diem_toi_da" varchar(100),
  "noi_dung" text,
  "id_nhom_tieu_chi" int
);

CREATE TABLE "lich_trinh" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten" varchar(255),
  "hoat_dong" varchar(255),
  "ngay_bat_dau" timestamptz,
  "ngay_ket_thuc" timestamptz,
  "id_nguoi_them" int,
  "id_hoc_ky" int,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "hoc_ky" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_hoc_ky" int UNIQUE,
  "ngay_bat_dau" timestamptz,
  "nam_hoc" int,
  "id_nguoi_them" int
);

CREATE TABLE "hoi_dong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ngay_gio" timestamptz,
  "phong" varchar(100),
  "ten_hoi_dong" varchar(255),
  "giai_doan" varchar(255),
  "nhom_nganh" varchar(255),
  "he_dao_tao" varchar(255),
  "id_hoc_ky" int,
  "id_nguoi_lap" int
);

CREATE TABLE "danh_gia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trang_thai" varchar(255),
  "id_hoi_dong" int,
  "id_de_tai" int
);

CREATE TABLE "phan_bien" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trang_thai" varchar(255),
  "id_giang_vien" int,
  "id_de_tai" int,
  "id_hoc_ky" int
);

CREATE TABLE "tai_lieu" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_tai_lieu" varchar(255),
  "url" varchar(255),
  "id_nhiem_vu" int,
  "id_thuc_hien" int,
  "id_bao_cao" int
);

CREATE TABLE "bao_cao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trang_thai" varchar(200),
  "noi_dung" text,
  "ngay_thuc_hien" timestamptz,
  "ngay_chinh_sua" timestamptz,
  "id_sinh_vien" int,
  "id_de_tai" int
);

CREATE TABLE "nhiem_vu" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten" varchar(255),
  "mo_ta" varchar(255),
  "ngay_bat_dau" timestamptz,
  "ngay_ket_thuc" timestamptz,
  "id_nguoi_them" int,
  "id_de_tai" int
);

CREATE TABLE "giao_vu" (
  "msnv" varchar(255) PRIMARY KEY,
  "chuc_vu" varchar(255),
  "id_tai_khoan" int UNIQUE
);

CREATE TABLE "giang_vien" (
  "msgv" varchar(255) PRIMARY KEY,
  "to_chuyen_nganh" varchar(255),
  "is_giang_vien_truong_bo_mon" bool,
  "id_tai_khoan" int UNIQUE
);

CREATE TABLE "sinh_vien" (
  "mssv" varchar(255) PRIMARY KEY,
  "nam_dao_tao" int,
  "he_dao_tao" varchar(255),
  "nganh" varchar(100),
  "ngon_ngu" varchar(100),
  "id_tai_khoan" int UNIQUE
);

CREATE TABLE "tai_khoan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_tai_khoan" varchar(255) UNIQUE,
  "mat_khau" varchar(255),
  "ten" varchar(255),
  "ho" varchar(255),
  "sdt" varchar(255) UNIQUE,
  "cccd" varchar(255) UNIQUE,
  "ngay_sinh" date,
  "email" varchar(255) UNIQUE,
  "dia_chi" varchar(255),
  "gioi_tinh" varchar(100),
  "vai_tro" varchar(100) NOT NULL
);

CREATE TABLE "chu_de" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_tieng_anh" text UNIQUE,
  "ten_tieng_viet" text UNIQUE
);

CREATE TABLE "duyet_de_tai" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_nguoi_duyet" int,
  "id_de_tai" int UNIQUE,
  "ngay_duyet" timestamptz,
  "trang_thai" varchar(100),
  "ghi_chu" varchar(255)
);

CREATE TABLE "moi_quan_tam" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_sinh_vien" int,
  "id_chu_de" int
);

CREATE TABLE "moi_lien_quan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_de_tai" int,
  "id_chu_de" int
);

CREATE TABLE "tham_gia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vai_tro" varchar(100),
  "id_giang_vien" int,
  "id_hoi_dong" int
);

CREATE TABLE "ket_qua" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "diem_chuyen_nganh" int,
  "diem_tot_nghiep" int,
  "id_sinh_vien" int UNIQUE,
  "id_de_tai" int
);

CREATE TABLE "thuc_hien" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trang_thai" varchar(100),
  "diem" int,
  "noi_dung" text,
  "ngay_thuc_hien" timestamptz,
  "ngay_chinh_sua" timestamptz,
  "id_sinh_vien" int,
  "id_nhiem_vu" int
);

CREATE TABLE "dang_ky" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ngay_dang_ky" timestamptz,
  "trang_thai" varchar(100),
  "id_sinh_vien" int,
  "id_de_tai" int
);

CREATE TABLE "huong_dan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vai_tro" varchar(100),
  "trang_thai" varchar(100),
  "id_giang_vien" int,
  "id_de_tai" int
);

CREATE TABLE "cham_diem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "giai_doan" varchar(255),
  "vai_tro" varchar(255),
  "id_giang_vien" int,
  "id_de_tai" int,
  "id_hoc_ky" int
);

CREATE TABLE "bang_diem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_sinh_vien" int,
  "id_cham_diem" int
);

CREATE TABLE "diem_thanh_phan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "diem" varchar(100),
  "id_bang_diem" int,
  "id_tieu_chi" int
);

CREATE TABLE "tuong_tac" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "da_doc_chua" bool,
  "thoi_diem_doc" timestamptz,
  "id_nguoi_nhan" int,
  "id_thong_bao" int
);

CREATE UNIQUE INDEX ON "moi_quan_tam" ("id_chu_de", "id_sinh_vien");

CREATE UNIQUE INDEX ON "moi_lien_quan" ("id_chu_de", "id_de_tai");

ALTER TABLE "de_tai" ADD FOREIGN KEY ("id_tai_khoan_de_xuat") REFERENCES "tai_khoan" ("id");

ALTER TABLE "thuoc_ve" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "thuoc_ve" ADD FOREIGN KEY ("id_hoc_ky") REFERENCES "hoc_ky" ("id");

ALTER TABLE "nhom_tieu_chi" ADD FOREIGN KEY ("id_mau_danh_gia") REFERENCES "mau_danh_gia" ("id");

ALTER TABLE "tieu_chi" ADD FOREIGN KEY ("id_nhom_tieu_chi") REFERENCES "nhom_tieu_chi" ("id");

ALTER TABLE "lich_trinh" ADD FOREIGN KEY ("id_nguoi_them") REFERENCES "giao_vu" ("id_tai_khoan");

ALTER TABLE "lich_trinh" ADD FOREIGN KEY ("id_hoc_ky") REFERENCES "hoc_ky" ("id");

ALTER TABLE "hoc_ky" ADD FOREIGN KEY ("id_nguoi_them") REFERENCES "giao_vu" ("id_tai_khoan");

ALTER TABLE "hoi_dong" ADD FOREIGN KEY ("id_hoc_ky") REFERENCES "hoc_ky" ("id");

ALTER TABLE "hoi_dong" ADD FOREIGN KEY ("id_nguoi_lap") REFERENCES "giang_vien" ("id_tai_khoan");

ALTER TABLE "danh_gia" ADD FOREIGN KEY ("id_hoi_dong") REFERENCES "hoi_dong" ("id");

ALTER TABLE "danh_gia" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "phan_bien" ADD FOREIGN KEY ("id_giang_vien") REFERENCES "giang_vien" ("id_tai_khoan");

ALTER TABLE "phan_bien" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "phan_bien" ADD FOREIGN KEY ("id_hoc_ky") REFERENCES "hoc_ky" ("id");

ALTER TABLE "tai_lieu" ADD FOREIGN KEY ("id_nhiem_vu") REFERENCES "nhiem_vu" ("id");

ALTER TABLE "tai_lieu" ADD FOREIGN KEY ("id_thuc_hien") REFERENCES "thuc_hien" ("id");

ALTER TABLE "tai_lieu" ADD FOREIGN KEY ("id_bao_cao") REFERENCES "bao_cao" ("id");

ALTER TABLE "bao_cao" ADD FOREIGN KEY ("id_sinh_vien") REFERENCES "sinh_vien" ("id_tai_khoan");

ALTER TABLE "bao_cao" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "nhiem_vu" ADD FOREIGN KEY ("id_nguoi_them") REFERENCES "giang_vien" ("id_tai_khoan");

ALTER TABLE "nhiem_vu" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "giao_vu" ADD FOREIGN KEY ("id_tai_khoan") REFERENCES "tai_khoan" ("id");

ALTER TABLE "giang_vien" ADD FOREIGN KEY ("id_tai_khoan") REFERENCES "tai_khoan" ("id");

ALTER TABLE "sinh_vien" ADD FOREIGN KEY ("id_tai_khoan") REFERENCES "tai_khoan" ("id");

ALTER TABLE "duyet_de_tai" ADD FOREIGN KEY ("id_nguoi_duyet") REFERENCES "giang_vien" ("id_tai_khoan");

ALTER TABLE "duyet_de_tai" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "moi_quan_tam" ADD FOREIGN KEY ("id_sinh_vien") REFERENCES "sinh_vien" ("id_tai_khoan");

ALTER TABLE "moi_quan_tam" ADD FOREIGN KEY ("id_chu_de") REFERENCES "chu_de" ("id");

ALTER TABLE "moi_lien_quan" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "moi_lien_quan" ADD FOREIGN KEY ("id_chu_de") REFERENCES "chu_de" ("id");

ALTER TABLE "tham_gia" ADD FOREIGN KEY ("id_giang_vien") REFERENCES "giang_vien" ("id_tai_khoan");

ALTER TABLE "tham_gia" ADD FOREIGN KEY ("id_hoi_dong") REFERENCES "hoi_dong" ("id");

ALTER TABLE "ket_qua" ADD FOREIGN KEY ("id_sinh_vien") REFERENCES "sinh_vien" ("id_tai_khoan");

ALTER TABLE "ket_qua" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "thuc_hien" ADD FOREIGN KEY ("id_sinh_vien") REFERENCES "sinh_vien" ("id_tai_khoan");

ALTER TABLE "thuc_hien" ADD FOREIGN KEY ("id_nhiem_vu") REFERENCES "nhiem_vu" ("id");

ALTER TABLE "dang_ky" ADD FOREIGN KEY ("id_sinh_vien") REFERENCES "sinh_vien" ("id_tai_khoan");

ALTER TABLE "dang_ky" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "huong_dan" ADD FOREIGN KEY ("id_giang_vien") REFERENCES "giang_vien" ("id_tai_khoan");

ALTER TABLE "huong_dan" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "cham_diem" ADD FOREIGN KEY ("id_giang_vien") REFERENCES "giang_vien" ("id_tai_khoan");

ALTER TABLE "cham_diem" ADD FOREIGN KEY ("id_de_tai") REFERENCES "de_tai" ("id");

ALTER TABLE "cham_diem" ADD FOREIGN KEY ("id_hoc_ky") REFERENCES "hoc_ky" ("id");

ALTER TABLE "bang_diem" ADD FOREIGN KEY ("id_sinh_vien") REFERENCES "sinh_vien" ("id_tai_khoan");

ALTER TABLE "bang_diem" ADD FOREIGN KEY ("id_cham_diem") REFERENCES "cham_diem" ("id");

ALTER TABLE "diem_thanh_phan" ADD FOREIGN KEY ("id_bang_diem") REFERENCES "bang_diem" ("id");

ALTER TABLE "diem_thanh_phan" ADD FOREIGN KEY ("id_tieu_chi") REFERENCES "tieu_chi" ("id");

ALTER TABLE "tuong_tac" ADD FOREIGN KEY ("id_nguoi_nhan") REFERENCES "tai_khoan" ("id");

ALTER TABLE "tuong_tac" ADD FOREIGN KEY ("id_thong_bao") REFERENCES "thong_bao" ("id");
